#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from source_layout_model import (
    SourceLayoutCollection,
    SourceLayoutCollectionMember,
    SourceLayoutIngestion,
    collection_member_ref,
    collection_member_to_config,
)
from tile_family_ingest import (
    bootstrap_family,
    compute_non_empty_tile_mask,
    compute_source_layout_coverage,
    detect_source_layout,
    load_source_tile_family,
    load_source_layout_from_path,
)
from tile_family_runtime import (
    AttachmentCanvasConfig,
    CompositeTileConfig,
    ConstructionAttachmentSetConfig,
    ConstructionAttachmentVariantConfig,
    ConstructionCellConfig,
    ConstructionConfig,
    ConstructionValidationError,
    DEFAULT_TRANSPARENT_MODE,
    FamilyCatalogSources,
    FamilyAliasesManifest,
    FamilyGridConfig,
    FamilyManifest,
    FamilyRenderDefaultsConfig,
    FamilyVariantConfig,
    FixedConstructionConfig,
    FixedConstructionSeamOverrideCellConfig,
    FixedConstructionSeamOverrideConfig,
    FrameCornerSlotConfig,
    FrameSlotConfig,
    ParametricFrameConstructionConfig,
    ParametricRunConstructionConfig,
    PlaceableRefConfig,
    TileFamily as RuntimeTileFamily,
    TileFamilyHeader,
    TileFamilyIngestReport,
    TileFamilyVariant,
    TileLibraryPromotedMetadata,
    build_construction,
    load_alias_manifest,
    load_attachment_manifest,
    load_attachment_sets_from_data,
    load_cluster_manifest,
    load_composite_tile_manifest,
    load_composite_tiles_from_data,
    load_construction_manifest,
    load_constructions_from_data,
    load_family_header_from_manifest,
    load_family_catalog_sources,
    load_family_header_and_variants,
    load_family_manifest,
    load_family_variants_from_manifest,
    load_tile_manifest,
    validate_construction,
)

__all__ = [
    "AttachmentCanvasConfig",
    "CompositeTileConfig",
    "ConstructionAttachmentSetConfig",
    "ConstructionAttachmentVariantConfig",
    "ConstructionCellConfig",
    "ConstructionConfig",
    "ConstructionValidationError",
    "DEFAULT_TRANSPARENT_MODE",
    "FamilyAliasesManifest",
    "FamilyCatalogSources",
    "FamilyGridConfig",
    "FamilyManifest",
    "FamilyRenderDefaultsConfig",
    "FamilyVariantConfig",
    "FixedConstructionConfig",
    "FixedConstructionSeamOverrideCellConfig",
    "FixedConstructionSeamOverrideConfig",
    "FrameCornerSlotConfig",
    "FrameSlotConfig",
    "ParametricFrameConstructionConfig",
    "ParametricRunConstructionConfig",
    "PlaceableRefConfig",
    "SourceLayoutCollection",
    "SourceLayoutCollectionMember",
    "SourceLayoutIngestion",
    "TileFamily",
    "TileFamilyHeader",
    "TileFamilyIngestReport",
    "TileFamilyVariant",
    "TileLibraryPromotedMetadata",
    "bootstrap_family",
    "build_construction",
    "collection_member_ref",
    "collection_member_to_config",
    "compute_non_empty_tile_mask",
    "compute_source_layout_coverage",
    "detect_source_layout",
    "load_alias_manifest",
    "load_attachment_manifest",
    "load_attachment_sets_from_data",
    "load_cluster_manifest",
    "load_composite_tile_manifest",
    "load_composite_tiles_from_data",
    "load_construction_manifest",
    "load_constructions_from_data",
    "load_family_catalog_sources",
    "load_family_header_and_variants",
    "load_family_header_from_manifest",
    "load_family_manifest",
    "load_family_variants_from_manifest",
    "load_source_tile_family",
    "load_source_layout_from_path",
    "load_tile_manifest",
    "validate_construction",
]

class TileFamily(RuntimeTileFamily):
    @classmethod
    def load(cls, family_dir: Path) -> TileFamily:
        return load_source_tile_family(family_dir, family_cls=cls)
